-- V6__more_auctions_for_infinite_scroll.sql
-- הוספת מכרזים נוספים עם תמונות קבועות לבדיקת infinite scroll

INSERT INTO auctions (
    title,
    description,
    condition,
    categories,
    image_urls,
    min_price,
    buy_now_price,
    bid_increment,
    current_bid_amount,
    start_date,
    end_date,
    seller_id,
    status,
    bids_count,
    created_at,
    updated_at
) VALUES 
-- מכרז 7
(
    'ספה תלת מושבית',
    'ספה נוחה במצב טוב, מתאימה לסלון',
    'used',
    '["furniture", "living_room"]',
    '["/images/placeholder1.jpg", "/images/placeholder2.jpg"]',
    800.00,
    1500.00,
    30.00,
    830.00,
    DATEADD('hour', -3, CURRENT_TIMESTAMP),
    DATEADD('day', 5, CURRENT_TIMESTAMP),
    1,
    'active',
    3,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- מכרז 8
(
    'רכב יונדאי i30',
    'רכב במצב טוב, שנת 2019, 45,000 ק"מ',
    'used',
    '["vehicles", "cars"]',
    '["/images/placeholder3.jpg"]',
    65000.00,
    80000.00,
    500.00,
    66000.00,
    DATEADD('hour', -5, CURRENT_TIMESTAMP),
    DATEADD('day', 8, CURRENT_TIMESTAMP),
    2,
    'active',
    12,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- מכרז 9
(
    'מיקסר KitchenAid',
    'מיקסר מקצועי במצב מעולה, כולל קערות',
    'like_new',
    '["kitchen", "appliances"]',
    '["/images/placeholder4.jpg", "/images/placeholder5.jpg"]',
    1200.00,
    1800.00,
    40.00,
    1240.00,
    DATEADD('hour', -1, CURRENT_TIMESTAMP),
    DATEADD('day', 4, CURRENT_TIMESTAMP),
    1,
    'active',
    5,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- מכרז 10
(
    'משחק פלייסטיישן 5',
    'קונסולת PS5 חדשה באריזה',
    'new',
    '["gaming", "consoles"]',
    '["/images/placeholder1.jpg"]',
    2200.00,
    2800.00,
    50.00,
    2250.00,
    DATEADD('minute', -45, CURRENT_TIMESTAMP),
    DATEADD('day', 3, CURRENT_TIMESTAMP),
    2,
    'active',
    8,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- מכרז 11
(
    'שולחן עבודה איקאה',
    'שולחן עבודה מעץ במצב מצוין',
    'used',
    '["furniture", "office"]',
    '["/images/placeholder2.jpg", "/images/placeholder3.jpg"]',
    350.00,
    600.00,
    15.00,
    365.00,
    DATEADD('hour', -2, CURRENT_TIMESTAMP),
    DATEADD('day', 6, CURRENT_TIMESTAMP),
    1,
    'active',
    4,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- מכרז 12
(
    'מצלמה Canon EOS R6',
    'מצלמה דיגיטלית מקצועית, כולל עדשות',
    'like_new',
    '["photography", "cameras"]',
    '["/images/placeholder4.jpg"]',
    8500.00,
    12000.00,
    200.00,
    8700.00,
    DATEADD('hour', -4, CURRENT_TIMESTAMP),
    DATEADD('day', 7, CURRENT_TIMESTAMP),
    2,
    'active',
    15,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- מכרז 13
(
    'טאבלט iPad Pro',
    'iPad Pro 12.9 אינץ, 256GB, Wi-Fi + Cellular',
    'used',
    '["electronics", "tablets"]',
    '["/images/placeholder5.jpg", "/images/placeholder1.jpg"]',
    3200.00,
    4500.00,
    80.00,
    3280.00,
    DATEADD('hour', -6, CURRENT_TIMESTAMP),
    DATEADD('day', 4, CURRENT_TIMESTAMP),
    1,
    'active',
    9,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- מכרז 14
(
    'אוזניות Bose',
    'אוזניות אלחוטיות עם ביטול רעש',
    'like_new',
    '["electronics", "audio"]',
    '["/images/placeholder2.jpg"]',
    850.00,
    1200.00,
    25.00,
    875.00,
    DATEADD('minute', -20, CURRENT_TIMESTAMP),
    DATEADD('day', 5, CURRENT_TIMESTAMP),
    2,
    'active',
    6,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- מכרז 15
(
    'מכונת כביסה LG',
    'מכונת כביסה 8 ק"ג, במצב מצוין',
    'used',
    '["appliances", "laundry"]',
    '["/images/placeholder3.jpg", "/images/placeholder4.jpg"]',
    1800.00,
    2500.00,
    50.00,
    1850.00,
    DATEADD('hour', -3, CURRENT_TIMESTAMP),
    DATEADD('day', 6, CURRENT_TIMESTAMP),
    1,
    'active',
    7,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- מכרז 16
(
    'ארון בגדים',
    'ארון בגדים גדול עם מראה, במצב טוב',
    'used',
    '["furniture", "bedroom"]',
    '["/images/placeholder5.jpg"]',
    1200.00,
    1800.00,
    40.00,
    1240.00,
    DATEADD('hour', -7, CURRENT_TIMESTAMP),
    DATEADD('day', 8, CURRENT_TIMESTAMP),
    2,
    'active',
    3,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- מכרז 17
(
    'אופניים חשמליים',
    'אופניים חשמליים עם סוללה חזקה',
    'like_new',
    '["sports", "electric_bikes"]',
    '["/images/placeholder1.jpg", "/images/placeholder3.jpg"]',
    4500.00,
    6500.00,
    100.00,
    4600.00,
    DATEADD('hour', -1, CURRENT_TIMESTAMP),
    DATEADD('day', 3, CURRENT_TIMESTAMP),
    1,
    'active',
    11,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- מכרז 18
(
    'מקרר סמסונג',
    'מקרר דלת צרפתית, נפח 500 ליטר',
    'used',
    '["appliances", "refrigerators"]',
    '["/images/placeholder2.jpg", "/images/placeholder4.jpg"]',
    2800.00,
    4000.00,
    75.00,
    2875.00,
    DATEADD('hour', -4, CURRENT_TIMESTAMP),
    DATEADD('day', 7, CURRENT_TIMESTAMP),
    2,
    'active',
    8,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- מכרז 19
(
    'מחשב גיימינג',
    'מחשב גיימינג עם RTX 4070, 32GB RAM',
    'like_new',
    '["electronics", "gaming"]',
    '["/images/placeholder5.jpg", "/images/placeholder1.jpg"]',
    8000.00,
    12000.00,
    200.00,
    8200.00,
    DATEADD('minute', -30, CURRENT_TIMESTAMP),
    DATEADD('day', 5, CURRENT_TIMESTAMP),
    1,
    'active',
    16,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- מכרז 20
(
    'מזרן אורתופדי',
    'מזרן זוגי איכותי במצב מעולה',
    'like_new',
    '["furniture", "bedroom"]',
    '["/images/placeholder3.jpg"]',
    1500.00,
    2200.00,
    50.00,
    1550.00,
    DATEADD('hour', -5, CURRENT_TIMESTAMP),
    DATEADD('day', 4, CURRENT_TIMESTAMP),
    2,
    'active',
    4,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- מכרז 21
(
    'כסא גיימינג',
    'כסא גיימינג ארגונומי עם תמיכה למותניים',
    'used',
    '["furniture", "gaming"]',
    '["/images/placeholder2.jpg", "/images/placeholder5.jpg"]',
    800.00,
    1300.00,
    30.00,
    830.00,
    DATEADD('hour', -2, CURRENT_TIMESTAMP),
    DATEADD('day', 6, CURRENT_TIMESTAMP),
    1,
    'active',
    5,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- מכרז 22
(
    'סמארטפון iPhone 14',
    'iPhone 14 Pro Max 256GB במצב מצוין',
    'like_new',
    '["electronics", "smartphones"]',
    '["/images/placeholder4.jpg", "/images/placeholder1.jpg"]',
    3800.00,
    4800.00,
    100.00,
    3900.00,
    DATEADD('hour', -3, CURRENT_TIMESTAMP),
    DATEADD('day', 3, CURRENT_TIMESTAMP),
    2,
    'active',
    14,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- מכרז 23
(
    'מכונת תפירה Brother',
    'מכונת תפירה ממוחשבת במצב מעולה',
    'used',
    '["crafts", "sewing"]',
    '["/images/placeholder3.jpg", "/images/placeholder2.jpg"]',
    1200.00,
    1800.00,
    40.00,
    1240.00,
    DATEADD('hour', -6, CURRENT_TIMESTAMP),
    DATEADD('day', 7, CURRENT_TIMESTAMP),
    1,
    'active',
    6,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- מכרז 24
(
    'רמקולים JBL',
    'רמקולים אלחוטיים עמידים במים',
    'new',
    '["electronics", "audio"]',
    '["/images/placeholder5.jpg"]',
    450.00,
    650.00,
    20.00,
    470.00,
    DATEADD('minute', -15, CURRENT_TIMESTAMP),
    DATEADD('day', 4, CURRENT_TIMESTAMP),
    2,
    'active',
    7,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
-- מכרז 25
(
    'מזגן אלקטרה',
    'מזגן אינוורטר 1.5 כ"ס במצב טוב',
    'used',
    '["appliances", "cooling"]',
    '["/images/placeholder1.jpg", "/images/placeholder4.jpg"]',
    2200.00,
    3000.00,
    60.00,
    2260.00,
    DATEADD('hour', -4, CURRENT_TIMESTAMP),
    DATEADD('day', 8, CURRENT_TIMESTAMP),
    1,
    'active',
    9,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);
